[workspace]
resolver = "2"
members = [
	"crates/*",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
criterion-cycles-per-byte = "0.6.1"
lazy_static = "1.5.0"
thiserror = "1.0.63"

