[package]
name = "dungers_bitbuf"
version = "0.0.0"
edition.workspace = true

[dependencies]
thiserror.workspace = true
lazy_static.workspace = true

[dev-dependencies]
criterion.workspace = true
criterion-cycles-per-byte.workspace = true

[[bench]]
name = "wrubit64"
harness = false
